<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.1.251">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>After accounting for state, which variable accounts for the most variability in median household income?</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>


</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="./index.html">TEAM NAME</a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./proposal.html">Proposal</a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./presentation.pdf">Presentation</a>
  </li>  
  <li class="nav-item">
    <a class="nav-link active" href="./report.html" aria-current="page">Report</a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./about.html">About</a>
  </li>  
</ul>
              <div id="quarto-search" class="" title="Search"></div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">After accounting for state, which variable accounts for the most variability in median household income?</h1>
<p class="subtitle lead">Report</p>
</div>



<div class="quarto-title-meta">

    
    
  </div>
  

</header>

<p><strong><em>Introduction</em></strong></p>
<p>There are persistent problems and injustices in the United States surrounding income inequality. For our research project, we are going to examine the question: After accounting for state, which variable accounts for the most variability in median household income? In order to investigate this question, we will look at data coming from over 3,000 counties and all 50 states in the United States. In many cases, income levels and location (such as more vulnerable states and counties) are very interrelated for families in terms of accessing improved educational opportunities and resources, causing or exacerbating a vicious cycle that can be hard to break. In America, there are many root causes that contribute to such a cycle, and it is important they are clearly researched and evaluated, so changes can start to be made to states and therefore, populations that need them most. There are many factors that can influence one’s career outcomes, but some particularly important ones that we are going to focus on are education level, ethnicity, gender, and age. According to the APLU, people who hold college degrees are twice as likely to get a job and make around an extra $1.2 million over the course of their life (APLU). Black or Latino families make around 50% of what white households do, according to the Federal Reserve Board (Federal Reserve Board). The gender pay gap still persists, with women earning an average of 82% of what men do (PEW Research Center). Income can also vary with age, as people’s income typically peaks right before retirement (so around age 65). It is also important to note that on the state level, various factors such as funding per county and class disparities impact income inequality as well, which is something that we could observe beyond this project after identifying states that are particularly vulnerable. There are intersections in everyone’s identities and, thereby the states’ identities as well, and when combined, can have even greater impacts on career outcomes, so knowing which specific identities are most vulnerable is also a key step to making actionable change. We believe states with residents with higher levels of education, a higher white population, and more males will have high median household incomes. Since this data has been gathered by the US Census Bureau, a government organization, there should be no ethical concerns. They adhere to strict privacy policy guidelines to ensure a confidential, respectful, and transparent experience for participants when collecting data (United States Census Bureau).</p>
<p><a href="https://www.census.gov/about/policies/privacy/data_stewardship/our_privacy_principles.html" class="uri">https://www.census.gov/about/policies/privacy/data_stewardship/our_privacy_principles.html</a></p>
<p><a href="https://www.aplu.org/our-work/4-policy-and-advocacy/publicuvalues/employment-earnings/#:~:text=The%20evidence%20that%20a%20college,on%20average%20over%20their%20lifetime" class="uri">https://www.aplu.org/our-work/4-policy-and-advocacy/publicuvalues/employment-earnings/#:~:text=The%20evidence%20that%20a%20college,on%20average%20over%20their%20lifetime</a>.</p>
<p><a href="https://www.federalreserve.gov/econres/notes/feds-notes/wealth-inequality-and-the-racial-wealth-gap-20211022.html#:~:text=In%20the%20United%20States%2C%20the,percent%20as%20much%20net%20wealth" class="uri">https://www.federalreserve.gov/econres/notes/feds-notes/wealth-inequality-and-the-racial-wealth-gap-20211022.html#:~:text=In%20the%20United%20States%2C%20the,percent%20as%20much%20net%20wealth</a>.</p>
<p><a href="https://www.pewresearch.org/fact-tank/2023/03/01/gender-pay-gap-facts/#:~:text=The%20gender%20gap%20in%20pay,%2D%20and%20part%2Dtime%20workers" class="uri">https://www.pewresearch.org/fact-tank/2023/03/01/gender-pay-gap-facts/#:~:text=The%20gender%20gap%20in%20pay,%2D%20and%20part%2Dtime%20workers</a>.</p>
<p><br>
<strong><em>Data</em></strong></p>
<p>The dataset we are analyzing is from The Collection of Really Great, Interesting, Situated Datasets (CORGIS) Project. The data was collected from 2010 to 2019 by the United States Census Bureau. It should be noted that some of the estimates came from sample data. The dataset includes a wide variety of observations for various counties in the United States. In order to best serve our research question, we will focus on the statistics such as education level, ethnicity, age, and gender as well as respective state and median household income. The data is largely qualitative and in terms of what percentage of the county fits a certain description such as being a high school graduate or white, although there are some quantitative variables such as state and county.<br>
</p>
<p><strong><em>Methodology</em></strong></p>
<p>We began by loading in the necessary libraries and obtained the county demographic data.</p>
<div class="cell">

</div>
<div class="cell">

</div>
<p><em>Renaming Variables</em></p>
<p>We renamed our variables of interest because our dataset’s variables were too long. We focused on the variables of median household income (“income”), the percentage of the county that had a bachelor’s degree or higher (“education”), the percentage of the county that was female (“percent_female”), the percentage of the county that was 65 years and older (“age”), and the percentage of the county that was White and not Hispanic (“percentage_white”).</p>
<div class="cell">

</div>
<p><em>Graph of Income Versus State</em></p>
<p>To start our exploratory data analysis, we wanted to see how income varied across states. So, we made a heat map of the United States with different colors denoting different median household income levels.</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="report_files/figure-html/income-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>We first summarized our data (finding median income) and manipulated it (using full_join) in order to create a Choropleth map of the US. Each state is colored based on median household income. We chose to create these maps as they helped us visualize general geographic patterns within the US based on the spectrum of colors by state. The states that are colored darker (such as purple and blue) have lower median household incomes, whereas those that are lighter colors (like yellow and green) are states that have higher median household incomes.</p>
<p>This visualization allows us to see that there are greater income disparities in the southeatern states, especially Mississippi, and that there is a generally higher median household income in the western and northeastern states, especially New Jersey.</p>
<p><em>Graphs of Income Versus Different Variables</em></p>
<p>Income vs.&nbsp;Education Level</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="report_files/figure-html/income-education-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>The line of best fit of this scatter plot suggests a moderately strong, positive correlation between median education level per county and median household income per county in thousands.</p>
<p>Income vs.&nbsp;Percent Female</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="report_files/figure-html/income-percent-female-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>The line of best fit of this scatter plot suggests no correlation, or an extremely weak positive correlation, between female percentages per county and median household income per county in thousands.</p>
<p>Income vs.&nbsp;Age 65 and Older</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="report_files/figure-html/income-age-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>The line of best fit of this scatter plot suggests no correlation, or an extremely weak positive correlation, between percent aged 65 and older per county and median household income per county in thousands.</p>
<p>Income vs.&nbsp;Percentage White</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="report_files/figure-html/income-ethnicity-white-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>The line of best fit of this scatter plot suggests a very weak positive correlation between white percentage per county and median household income per county in thousands.</p>
<p>Given the results of these preliminary visuals, it seems as though education will be the variable that accounts for the most variability in median household income.</p>
<p><em>Models (Linear Regressions)</em></p>
<p>Baseline Model</p>
<p>Before we created any additive models, we first created a baseline model that only looked at median household income for all of the states. We created a linear regression because the response variable was numeric (median household income). The r-squared value for this model was 0.2923676, meaning that around 29% of the variability in median household income is due to the state.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>parsnip model object


Call:
stats::lm(formula = income ~ State, data = data)

Coefficients:
(Intercept)      StateAL      StateAR      StateAZ      StateCA      StateCO  
    68491.5     -24916.6     -26254.8     -19501.5       -777.9      -9696.7  
    StateCT      StateDC      StateDE      StateFL      StateGA      StateHI  
    10709.9      17928.5      -2503.5     -17201.3     -21261.8       7937.1  
    StateIA      StateID      StateIL      StateIN      StateKS      StateKY  
   -11231.9     -17569.8     -11835.2     -12624.9     -15626.8     -23609.3  
    StateLA      StateMA      StateMD      StateME      StateMI      StateMN  
   -23617.5       9254.1       9050.1     -14922.7     -16683.1      -6835.0  
    StateMO      StateMS      StateMT      StateNC      StateND      StateNE  
   -20395.4     -28878.4     -17507.5     -20072.0      -6016.1     -13796.5  
    StateNH      StateNJ      StateNM      StateNV      StateNY      StateOH  
      816.7      14395.7     -24768.5      -8371.8      -6006.9     -12691.2  
    StateOK      StateOR      StatePA      StateRI      StateSC      StateSD  
   -19780.8     -14538.4     -11435.4       7622.9     -22883.2     -13870.1  
    StateTN      StateTX      StateUT      StateVA      StateVT      StateWA  
   -21324.5     -15643.9      -5431.9      -7734.7      -8731.7      -9098.0  
    StateWI      StateWV      StateWY  
   -10185.6     -23599.2      -6662.8  </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.2923676</code></pre>
</div>
</div>
<p>Next, we created four different linear regression models that combined state with each variable to see which variable, when combined with state, resulted in the highest variability in median household income. We used r-squared values because each of these models only had 2 variables, so the number of variables would not have an effect on r-squared. We also used additive models instead of interaction models because if we used interaction models, there would be too many coefficients (because of each state). Therefore, for the purposes of clarity, we decided to use additive models. However, in future projects, we could look into interaction models.</p>
<p>Model with State and Education</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.6129233</code></pre>
</div>
</div>
<p>According to the r-squared value of 0.6129233, our additive model with state and education explains roughly 61% of the variability in median household income.</p>
<p>Model with State and Percent Female</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.2956188</code></pre>
</div>
</div>
<p>According to the r-squared value of 0.2956188, our additive model with state and the percentage of people who are female explains roughly 61% of the variability in median household income.</p>
<p>Model with State and Age 65 and Older</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.3746036</code></pre>
</div>
</div>
<p>According to the r-squared value of 0.3746036, our additive model with state and the percentage of people who are 65 years and older explains roughly 37% of the variability in median household income.</p>
<p>Model with State and Percentage White</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.2985728</code></pre>
</div>
</div>
<p>According to the r-squared value of 0.2985728, our additive model with state and the percentage of people who are White and not Hispanic or Latino explains roughly 30% of the variability in median household income.</p>
<p><strong><em>Results</em></strong></p>
<p>A higher r-squared value means that a greater percentage of the variability in the dependent variable can be explained by the independent variables. In this case, the dependent variable was median household income. Before creating any additive models, we created a baseline linear regression model that solely focused on the relationship between state and median household income. According to the r-squared value of 0.2923676, around 29% of the variability in median household income is due to the state. We then compared this r-squared value to r-squared values of the four additive models. The r-squared values for state and each of the independent variables for education, age, gender, and ethnicity, respectively, are 0.6129, 0.3746, 0.2956, and 0.2986. Therefore, as the r-squared value for education was the highest (increased the most from the baseline model), it is the best predictor of median household income (when coupled with state) among these four explanatory variables. Additionally, based on the graphs for each variable, education vs.&nbsp;income was also the only graph with a best-fit line with a positive slope.</p>
<p>After the state and education model, the next best model was the additive model with state and the percentage of people who are 65 years and older. The r-squared value was 0.3746, meaning the additive model explains roughly 37% of the variation in median household income. This was not much of an increase from the baseline model that only examined the state. This makes sense because from our exploratory data analysis, the graph of median household income versus percentage of people 65 years and older had a relatively weak and flat correlation.</p>
<p>The worst models was the additive model with state and the percentage of people who are White and the additive model with state and the percentage of people who are female. The r-squared value for the first model was 0.2985728, meaning this additive model explains roughly 30% of the variation in median household income. The r-squared value for the second model was 0.2956188, meaning this additive model explains roughly 30% of the variation in median household income. These r-squared values are also not much higher than the r-squared value of the baseline model, which makes sense because the graphs for these variables were relatively weak and flat. The coefficients for each state for the linear regression models represent the change in income for each state compared to the intercept, which is Alaska’s median household income. Excluding Washington D.C., the state with the highest income was New Jersey, with a coefficient of 14395.7, and the state with the lowest income was Mississippi, with a coefficient of -28878.4.</p>
<p><strong><em>Discussion</em></strong></p>
<p>The state of New Jersey had the third highest coefficient (1259.7) in the fitted model between income, state, and education, and Mississippi had the lowest coefficient (-23261.6527). Given that New Jersey was the highest median household income and Mississippi had the lowest, the results of the education model strongly support the conclusion that education is the variable that most accounts for variability in median household income across states. While we were able to make some preliminary observations about what general factors had the largest impact on median household income by state, there were some crucial limitations of our project. First, the only income variable that was in the dataset was median household income which could have limitations and does not take into account the extremes on either side of the income spectrum. If the dataset had the mean household incomes, this could have provided a clearer picture of income disparities within and between states. The dataset was also created in terms of percentages of people who fit into a single category which limited whether we could look at multiple categories at once. For example, when it came to age there were categories for under 5-years-old, under 18-years-old, and over 65-years-old. This was limiting as most people who are earning income are in between 18 to 65 years old. So, we thought that using the 65 and older category was most fitting, but it likely led to over-generalization of trends that occur.</p>
<p>There are several future steps our group could take to improve our analysis. In this project we focused on how the factors of ethnicity, gender, education level, and age, when added with state, impacted median household income on the state level, but since the dataset is also organized by counties we could further our analysis to the county level. Now knowing that a state such as Mississippi is more vulnerable in terms of lower median household income and lower education levels, we could focus our research on specific counties in Mississippi that have particularly low income and education levels in order to help them get on track on a path towards higher median household income and education levels. Moreover, making our explanatory variables more nuanced would allow us to get a better idea of how education levels, for example, impact median household income. To do this, rather than just splitting up education levels into Bachelor’s degree and no Bachelor’s degree we could separate education levels into no degree, high school degree, and Bachelor’s degree. Another explanatory variable that could be more nuanced is ethnicity as we separated ours into White and non-White. It is important to recognize that not all ethnic minorities have the same experiences so splitting this variable up could lead to more detailed findings. Unfortunately, the way our dataset was organized made it extremely confusing and difficult to separate the ethnic minorities accurately.</p>
<p>Lastly, we used additive models rather than interaction models. Interaction models could have given us a lens into how the independent variables interacted with each other and could have led to some different findings than the additive models did. Due to the inter-sectionality of one’s identity, we would guess that the independent variables are interconnected.</p>



</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    setTimeout(function() {
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const cites = ref.parentNode.getAttribute('data-cites').split(' ');
    tippyHover(ref, function() {
      var popup = window.document.createElement('div');
      cites.forEach(function(cite) {
        var citeDiv = window.document.createElement('div');
        citeDiv.classList.add('hanging-indent');
        citeDiv.classList.add('csl-entry');
        var biblioDiv = window.document.getElementById('ref-' + cite);
        if (biblioDiv) {
          citeDiv.innerHTML = biblioDiv.innerHTML;
        }
        popup.appendChild(citeDiv);
      });
      return popup.innerHTML;
    });
  }
});
</script>
</div> <!-- /content -->



</body></html>